#!/bin/bash

for foo in "${@}"; do
  foo="${foo//o/0}"
  foo="${foo//l/1}"
  foo="${foo//\+/-}"
  foo="${foo//s/5}"
  foo="${foo//t/7}"
  foo="${foo//i/1}"
  foo="${foo//a/4}"
  foo="${foo//e/3}"
  echo "${foo}"
done
