#!/bin/bash

if [[ -z "${1}" ]]; then
  echo "Usage: `basename ${0}` <files>"
  exit 1
fi

green="\033[01;32m"
red="\033[01;31m"
none="\033[00m"
ok="[  ${green}ok${none}  ]"
fail="[ ${red}fail${none} ]"

while [[ -n "${1}" ]]; do
  if [[ ! -f "${1}" ]]; then
    echo -e "${fail} ${1} does not exist"
  else
    if perl -pi -e 's/\r\n/\n/' "${1}"; then
      echo -e "${ok} ${1}"
    else
      echo -e "${fail} ${1}"
    fi
  fi

  shift
done

exit 0
