#!/bin/bash

if [[ -z "${1}" ]]; then
  echo "Usage: $(basename "${0}") <files>"
  exit 1
fi

if [[ -n "${FORCE_COLOR}" || ( -t 1 && "$(tput colors 2>/dev/null)" -gt 0 ) ]]; then
  green="\033[01;32m"
  red="\033[01;31m"
  reset="\033[00m"
else
  green=
  red=
  reset=
fi

ok="${green}ok${reset}"
fail="${red}fail${reset}"

while [[ -n "${1}" ]]; do
  if perl -pi -e 's/\r\n/\n/' "${1}"; then
    echo -e "${1}: ${ok}"
  else
    echo -e "${1}: ${fail}"
  fi

  shift
done
