#!/bin/bash

_help() {
	echo 'usage: git snap [--branch=current] [filename]'
	exit 1
}

DIR=${PWD}
while [[ -n ${DIR} && ${DIR} != '/' && ! -d ${DIR}/.git ]]; do
	DIR=${DIR%/*}
done
if [[ -z ${DIR} ]]; then
	echo 'not a git repository!'
	exit 2
fi

REPO=${DIR##*/}

while [[ -n ${1} ]]; do
	case ${1} in
		--branch=*)
			BRANCH=${1/--branch=/}
			;;
		--*)
			_help
			;;
		*)
			if [[ -z ${OUTPUT} ]]; then
				OUTPUT=${1}
			else
				_help
			fi
			;;
	esac

	shift
done

if [[ -z ${BRANCH} ]]; then
	BRANCH=`git symbolic-ref HEAD 2>/dev/null`
	BRANCH=${BRANCH#refs/heads/}
fi

if [[ -z ${OUTPUT} ]]; then
	OUTPUT="${REPO}-${BRANCH}.tar.gz"
	FORMAT='tar'
	FILTER='gzip'
else
	case ${OUTPUT} in
		*.tar.gz)
			FORMAT='tar'
			FILTER='gzip'
			;;
		*.tar.bz2)
			FORMAT='tar'
			FILTER='bzip2'
			;;
		*.tar)
			FORMAT='tar'
			FILTER=''
			;;
		*.zip)
			FORMAT='zip'
			FILTER=''
			;;
		*)
			echo 'unknown file format'
			exit 3
			;;
	esac
fi


if [[ ${FORMAT} == 'zip' ]]; then
	git archive ${BRANCH} --format=zip > ${OUTPUT}
elif [[ -n ${FILTER} ]]; then
	git archive ${BRANCH} --format=tar | ${FILTER} > ${OUTPUT}
else
	git archive ${BRANCH} --format=tar > ${OUTPUT}
fi
