#!/bin/bash

#
# usage
#

usage() {
  echo 'Usage: git lf [options]'
  echo
  echo 'Options:'
  echo '  -h, --help            Print this message and exit'
  echo '  -t, --top=N           Take top N (default: 20)'
  exit ${1}
}

#
# parse command line arguments
#

TOP='20'
ARGS=()

PARSE='true'
while [[ -n "${1}" ]]; do
  if ${PARSE}; then
    case "${1}" in
      -h|--help)
        usage 0;;
      -t*)
        TOP="${1:2}";;
      --top=*)
        TOP="${1:5}";;
      -t|--top=)
        TOP="${2}"; shift;;
      --)
        PARSE='false';;
      -*)
        echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
      *)
        ARGS+=("${1}");;
    esac
  else
    ARGS+=("${1}")
  fi

  shift
done

set -- "${ARGS[@]}"

#
# check args
#

if [[ -z "${TOP}" || ! "${TOP}" =~ ^[0-9]+$ ]]; then
  echo "git-lf: Invalid TOP value: ${TOP}" >&2
  echo >&2
  usage 1>&2
fi

if [[ "${TOP}" = '0' ]]; then
  TOP='2147483647'  # 2^31 - 1
fi

#
# do some actual work
#

GIT_DIR="${PWD}"
while [[ ! -e "${GIT_DIR}/.git" && "${GIT_DIR}" != '/' && -n "${GIT_DIR}" ]]; do
  GIT_DIR="${GIT_DIR%/*}"
done

if [[ -z "${GIT_DIR}" || "${GIT_DIR}" = '/' ]]; then
  echo 'git-lf: not a git repository!' >&2
  exit 1
fi

GIT_DIR="${GIT_DIR}/.git"

{
  echo 'SHA|Size|Packed|Path'
  echo ':separator:'
  git verify-pack -v ${GIT_DIR}/objects/pack/pack-*.idx | grep ' blob ' | sort -k3nr | head -n ${TOP} | while read OBJECT; do
    set -- ${OBJECT}
    SHA="${1}"
    UNPACKED_SIZE="${3}"
    PACKED_SIZE="${4}"
    FILE=$(git --git-dir="${GIT_DIR}" rev-list --all --objects | grep "${SHA}" | cut -f2 -d' ')
    echo "${SHA}|${UNPACKED_SIZE}|${PACKED_SIZE}|${FILE}"
  done
} | text-table -a2:right -a3:right
