#!/bin/bash

#
# Usage
#

usage() {
  echo 'Usage:'
  echo "  ${0} [options]"
  echo
  echo 'Options:'
  echo '  -h, --help                Print this message'
  echo '  -s S, --server=S          SSH server (required if default is not set)'
  echo '  -l P, --local-port=P      Set local port (required)'
  echo '  -r P, --remote-port=P     Set remote port (optional)'
  echo '  -D, --save-default        Save server option to ~/.grok/server'
  exit "${1}"
}

#
# Default values
#

SERVER=''
[[ -f "${HOME}/.grok/server" ]] && SERVER="$(<"${HOME}/.grok/server")"
LOCAL_PORT=''
REMOTE_PORT=''
SAVE_DEFAULT='false'

ARGS=()
PARSE='true'

#
# Parse arguments
#

while [[ -n "${1}" ]]; do
  if ${PARSE}; then
    case "${1}" in
      -h|--help)
        usage 0;;

      --server=*)  SERVER="${1:9}";;
      -s|--server) SERVER="${2}"; shift;;
      -s*)         SERVER="${1:2}";;

      --local-port=*)  LOCAL_PORT="${1:13}";;
      -l|--local-port) LOCAL_PORT="${2}"; shift;;
      -l*)             LOCAL_PORT="${1:2}";;

      -r|--remote-port) REMOTE_PORT="${2}"; shift;;
      --remote-port=*)  REMOTE_PORT="${1:14}";;
      -r*)              REMOTE_PORT="${1:2}";;

      -D|--save-default) SAVE_DEFAULT='true';;

      --) PARSE='false';;
      -*) echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
      *)  ARGS+=("${1}");;
    esac
  else
    ARGS+=("${1}")
  fi

  shift
done

#
# Check options.
#

if [[ -z "${LOCAL_PORT}" ]]; then
  echo "${0}: missing required option --local-port" >&2
  echo >&2
  usage 1
fi

[[ -z "${REMOTE_PORT}" ]] && REMOTE_PORT="${LOCAL_PORT}"

if [[ -z "${SERVER}" ]]; then
  echo "${0}: missing required option --server" >&2
  echo >&2
  usage 1
fi

#
# Store default.
#

if ${SAVE_DEFAULT}; then
  mkdir -p "${HOME}/.grok"
  echo -n "${SERVER}" > "${HOME}/.grok/server"
fi

#
# Do the magic.
#

ssh -TnNqR "0.0.0.0:${REMOTE_PORT}:localhost:${LOCAL_PORT}" "${ARGS[@]}" "${SERVER}"
