#!/bin/bash

green="\033[01;32m"
red="\033[01;31m"
none="\033[00m"
ok="[  ${green}ok${none}  ]"
fail="[ ${red}fail${none} ]"

keep=false

if [[ "${1}" = '--keep' ]]; then
  keep=true
  shift
fi

if [[ -z "${1}" ]]; then
  echo "Usage: `basename ${0}` [--keep] <files>"
  exit 1
fi

while [[ -n "${1}" ]]; do
  ifile="${1}"
  ofile="${1%gz}"bz2

  if [[ "${ifile}" = "${ofile}" ]]; then
    ofile="${ifile}.bz2"
  fi

  if [[ ! -f "${ifile}" ]]; then
    echo -e "${fail} ${ifile} does not exist!"
    continue
  fi

  if gzip --test -- "${ifile}" >/dev/null 2>&1; then
    if gzip -d < "${ifile}" | bzip2 --best > "${ofile}"; then
      echo -e "${ok} ${ifile} -> ${ofile}"

      if ! ${keep}; then
        rm -f -- "${ifile}"
      fi
    else
      echo -e "${fail} ${ifile} -> ${ofile}"
    fi
  else
    echo "${fail} ${ifile} is not gzip compressed!"
  fi

  shift
done
