#!/bin/bash

if [ -z "$1" ] || [ "$1" = "--keep" ] && [ -z "$2" ]; then
    echo "Usage: `basename $0` [--keep] <files>"
    exit 1
fi

keep=""
if [ "$1" = "--keep" ]; then
    keep="keep"
    shift
fi

green="\033[01;32m"
red="\033[01;31m"
none="\033[00m"
ok="[  ${green}ok${none}  ]"
fail="[ ${red}fail${none} ]"

while [ ! -z "$1" ]; do
    ifile="$1"
    ofile="`echo "$1" | sed 's/gz$/bz2/g'`"
    if [ "$ifile" = "$ofile" ]; then
        ofile="$ifile.bz2"
    fi
    [ ! -f "$ifile" ] && echo -e "$fail $ifile does not exist!" || (gzip --test -- "$ifile" > /dev/null 2>&1 && (gzip -d < "$ifile" | bzip2 --best > "$ofile" && (echo -e "$ok $ifile -> $ofile"; [ -z "$keep" ] && rm -f -- "$ifile") || echo -e "$fail $ifile -> $ofile")) || echo -e "$fail $ifile is not gzip compressed"
    shift
done

exit 0
