#!/bin/bash

echo
if [ ! -f ${HOME}/.motd ]; then
  uname -sr
else
  IFS=$'\n'
  ARR=($(< ${HOME}/.motd))
  IFS=''
  i=0

  while [[ ! -z "${ARR[$i]}" ]]; do
    echo -e ${ARR[$i]}
    i=$((i + 1))
  done
fi
echo
