#!/bin/bash

if [[ $OSTYPE = freebsd* ]]; then
  ps_command() {
    ps -Awwo vsz,command
  }
else
  ps_command() {
    ps -Awwo size,command
  }
fi

psmem_command() {
  ps_command | tail -n +2 | awk '{ $1 = sprintf("%.2f", $1/1024); print }'
}

if [[ -n "${1}" ]]; then
  psmem_command | grep -E "${1}" | grep -vE '(grep|psmem) ' | awk '{ sum += $1 } END { printf("%0.2f\n", sum) }'
else
  psmem_command | grep -v '^0\.00 ' | sort --general-numeric-sort --reverse
fi
