#!/bin/bash

#
# Usage
#

usage() {
  echo 'Usage:'
  echo "  ${0} [options] <archive.ext> <files...>"
  echo
  echo '  * Extension can be on of: tar tar.gz tgz tar.bz2 tbz2 tar.lzma tar.xz txz .tar.zst tzst'
  echo
  echo 'Options:'
  echo '  -t, --threads=N           Execute N parallel threads or processes (default: 1)'
  exit ${1}
}

#
# Default values
#

THREADS=1
ARGS=()
PARSE=true

#
# Parse arguments
#

while [[ -n "${1}" ]]; do
  if ${PARSE}; then
    case "${1}" in
      -h|--help)
        usage 0;;

      -t|-T|--threads)
        THREADS="${2}"; shift;;
      --threads=*)
        THREADS="${1:10}";;
      -t*|-T*)
        THREADS="${1:2}";;

      --)
        PARSE=false;;
      -*)
        echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
      *)
        ARGS+=("${1}");;
    esac
  else
    ARGS+=("${1}")
  fi

  shift
done

set -- "${ARGS[@]}"

#
# Check archive name
#

ARCHIVE="${1}"
shift

if [[ -z "${ARCHIVE}" ]]; then
  echo "${0}: missing required argument" >&2
  echo >&2
  usage 1 >&2
fi

#
# Check file names
#

if [[ -z "${1}" ]]; then
  echo "${0}: you should provide at least one more argument"
  echo >&2
  usage 1 >&2
fi

#
# Check threads value
#

if [[ ! "${THREADS}" =~ ^[0-9]+$ ]]; then
  echo "${0}: invalid threads value: ${THREADS}" >&2
  echo >&2
  exit 1
fi

#
# Check compression & level
#

COMPRESSOR=
COMPRESSOR_ARGS=

COMPRESSION="${ARCHIVE##*.}"
case "${COMPRESSION}" in
  gz|tgz)
    if [[ ${THREADS} -gt 1 ]]; then
      COMPRESSOR=pigz
      COMPRESSOR_ARGS=("-p${THREADS}" '-9')
    else
      COMPRESSOR=gzip
      COMPRESSOR_ARGS=('-9')
    fi
    ;;
  bz2|tbz2)
    if [[ ${THREADS} -gt 1 ]]; then
      COMPRESSOR=pbzip2
      COMPRESSOR_ARGS=("-p${THREADS}" '-9')
    else
      COMPRESSOR=bzip2
      COMPRESSOR_ARGS=('-9')
    fi
    ;;
  lzma|xz|txz)
    if [[ ${THREADS} -gt 1 ]]; then
      COMPRESSOR=xz
      COMPRESSOR_ARGS=("-T${THREADS}" '-9')
    else
      COMPRESSOR=xz
      COMPRESSOR_ARGS=('-9')
    fi
    ;;
  zst|tzst)
    if [[ ${THREADS} -gt 1 ]]; then
      COMPRESSOR=zstd
      COMPRESSOR_ARGS=("-T${THREADS}" '-19')
    else
      COMPRESSOR=zstd
      COMPRESSOR_ARGS=('-19')
    fi
    ;;
  tar)
    :
    ;;
  *)
    echo "${0}: unknown compression: ${COMPRESSION}" >&2
    echo >&2
    usage 1 >&2
    ;;
esac

#
# Do the actual work
#

if [[ -z "${COMPRESSOR}" ]]; then
  tar cf "${ARCHIVE}" "${@}"
else
  tar c "${@}" | "${COMPRESSOR}" "${COMPRESSOR_ARGS[@]}" > "${ARCHIVE}"
fi
