#!/bin/bash

#
# usage
#

usage() {
  echo 'usage:'
  echo "  ${0} [options]"
  echo
  echo 'options:'
  echo '  -S, --session-name=S          set session name'
  exit "${1}"
}

#
# parse args
#

ARGS=()
PARSE=true
while [[ -n "${1}" ]]; do
  if ${PARSE}; then
    case "${1}" in
      -h|--help)
        usage 0;;

      -R|-r|-S|-s|--session-name)
        SESSION_NAME="${2}"; shift;;
      --session-name=*)
        SESSION_NAME="${1:15}";;
      -R*|-r*|-S*|-s*)
        SESSION_NAME="${1:2}";;

      --)
        PARSE=false;;
      *)
        ARGS+=("${1}");;
    esac
  else
    ARGS+=("${1}")
  fi

  shift
done

#
# find original tmux
#

for f in '/usr/bin/tmux' '/usr/local/bin/tmux'; do
  if [[ -x "${f}" ]]; then
    TMUX="${f}"
    break
  fi
done

if [[ -z "${TMUX}" ]]; then
  echo "${0}: tmux not found" >&2
  exit 1
fi

#
# tmuxify
#

if [[ -n "${SESSION_NAME}" ]]; then
  "${TMUX}" attach-session -t "${SESSION_NAME}" 2>/dev/null || {
    echo "tmux session '${SESSION_NAME}' not found, starting a new one..." >&2
    "${TMUX}" new-session -s "${SESSION_NAME}"
  }
else
  "${TMUX}" "${ARGS[@]}"
fi
