#!/bin/bash

if [[ -z "${1}" ]]; then
  echo "Usage: `basename ${0}` <archive.tar.xz> [files...]"
  exit 1
fi

if [[ -z "${2}" ]]; then
  set "${1}" "${1}"
fi

out="${1%/}"
shift

case ${out} in
  *.txz | *.tar.xz)
    tar -c -- "${@}" | lzma --best > "${out}"
    ret=$?
    ;;
  *)
    tar -c -- "${@}" | lzma --best > "${out}.tar.xz"
    ret=$?
    ;;
esac

case ${ret} in
  0)
    echo 'Done!'
    ;;
  *)
    echo 'Unknown error!'
    ;;
esac

exit ${ret}
