## Here is an example for Makefiles.

syntax "makefile" "Makefile[^/]*$" "\.(make|mk)$"
comment "#"

## Assignments.
color red "[:=]"

## Conditionals.
color magenta "\<(if|ifeq|else|endif)\>"

## Variables.
color cyan "\$+[{(][a-zA-Z0-9_-]+[})]"

## Targets.
color brightblue "^[^ 	]+:"

## Comments.
color green "#.*$"

## Trailing whitespace.
color ,green "[[:space:]]+$"
