#!/bin/bash

awsprofile() {
  if [[ -z "${1}" ]]; then
    awk '/\[profile/ { gsub(/\]/, ""); print $2 }' <"${HOME}/.aws/config"
  else
    export AWS_PROFILE="${1}"
  fi
}

__prompt_command_aws_hook() {
  if [[ -n "${AWS_PROFILE}" ]]; then
    local reset='\[\033[0m\]' grey='\[\033[1;30m\]' cyan='\[\033[0;36m\]'
    local aws="{${grey}aws:${cyan}${AWS_PROFILE}${reset}}"
    __prompt_string="${__prompt_string}${aws}"
  fi
}

__prompt_command_hooks+=('__prompt_command_aws_hook')
