#!/bin/bash

#
# convinently wrap git in a function and scan for local .gitconfigs
#

git() {
  local dir="${PWD}"

  while true; do
    if [[ -f "${dir}/.gitconfig" ]]; then
      env GIT_CONFIG="${dir}/.gitconfig" git "${@}"
      return ${?}
    fi

    dir="${dir%/*}"
    [[ "${dir}" = '/' || "${dir}" = '' ]] && break
  done

  command git "${@}"
}
