#!/bin/bash

if [[ -d "${HOME}/KubeConf" ]]; then
  #
  # bash prompt command hook
  #

  prompt_command_k8s_hook() {
    if [[ -n ${KUBECONFIG} ]]; then
      local reset='\[\033[0m\]' grey='\[\033[1;30m\]' cyan='\[\033[0;36m\]'
      local k8s="${KUBECONFIG##*/}";
      k8s="{${grey}k8s:${cyan}${k8s%.kubeconfig}${reset}}"
      __prompt_string="${__prompt_string}${k8s}"
    fi
  }

  prompt_command_hooks+=('prompt_command_k8s_hook')

  #
  # create functions that activate each env
  #

  shopt -s nullglob
  for file in "${HOME}/KubeConf"/*.kubeconfig; do
    base="${file##*/}"
    base="${base%.*}"
    eval "${base}() { echo 'Activating \"${base}\" k8s env...'; export KUBECONFIG=\"${file}\"; }"
  done
  shopt -u nullglob
fi
