#!/bin/bash

# set the internal field spereator to line break, so that we can iterate easily over the verify-pack output
IFS=$'\n';

# list all objects including their size, sort by size, take top 25
objects=`git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head -n 25`

output='Size,Compressed,SHA,Location'
for y in ${objects}
do
	# extract the size in bytes
	size=$((`echo ${y} | cut -f 5 -d ' '`/1024))

	# extract the compressed size in bytes
	compressed_size=$((`echo ${y} | cut -f 6 -d ' '`/1024))

	# extract the SHA
	sha=`echo ${y} | cut -f 1 -d ' '`

	# find the objects location in the repository tree
	other=`git rev-list --all --objects | grep ${sha}`

	# append to teh output
	output="${output}\n${size}k,${compressed_size}k,${other}"
done

echo -e ${output} | column -t -s ', '
