#!/bin/bash

if [[ -z "${1}" ]]; then
    echo "Usage: `basename ${0}` <file.tar.bz2> [files...]"
    exit 1
fi

if [[ -z "${2}" ]]; then
    set "${1}" "${1}"
fi

out=${1%/}
shift

case ${out} in
    *.tbz2 | *.tar.bz2)
        tar -c -- "${*}" | bzip2 --best > ${out}
        ret=$?
        ;;
    *)
        tar -c -- "${*}" | bzip2 --best > ${out}.tar.bz2
        ret=$?
        ;;
esac

case ${ret} in
    0)
        echo 'Done!'
        ;;
    *)
        echo 'Unknown error!'
        ;;
esac

exit ${ret}
